[project]
name = "python-idempotency"
version = "0.1.0"
description = "A lightweight idempotency middleware for FastAPI"
authors = [{ name="Ahmad Yusuf Ardabilli" }]
readme = "README.md"
requires-python = ">=3.9"

[project.urls]
Homepage = "https://github.com/ArdaBilly1/py-dempotency"